name: Infratools image - lint stage
on: push

jobs:
  lint-dockerfile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          files: Dockerfile

  security-scan:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t mrgreyves/infratools:${{ github.sha }} .
          trivy image mrgreyves/infratools:${{ github.sha }}
