name: Push infratools image
on:
  release:
    types: [published]

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          export infraimagetag=$(echo ${GITHUB_REF} | sed 's|refs/tags/||')
          docker build -t mrgreyves/infratools:${infraimagetag} .

      - name: Push Docker image
        run: |
          export infraimagetag=$(echo ${GITHUB_REF} | sed 's|refs/tags/||')
          docker push mrgreyves/infratools:${infraimagetag}
