name: Build simple flask app image
on: push

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint@v2
        with:
          files: Dockerfile
